### ISSUE TITLE
Refactor hls.js to use CML's ID3 utilities

### ISSUE THREAD

**Issue by littlespex** [streaming-video-technology-alliance/common-media-library#58]
**Is your feature request related to a problem? Please describe.**
The ID3 utility functions in CML are based in part on the ones in `hls.js`. Now that the ID3 functionality has been consolidated from the player libraries, the players should be refactored to use CML's version.

**Describe the solution you'd like**
Refactor `hls.js` to use CML's ID3 utilities.

**Comment by fyoungqualabs** [comment]
**What we just did:**
- Replaced ID3 parsing functions in src/demux/id3.ts within HLS.js with their counterparts from the Common Media Library.
- Identified tests in HLS.js that are now redundant, as they cover functionality moved to the Common Media Library.
**What we are planning to do next**
- Transfer these tests to the Common Media Library to ensure continued test coverage(some of them might already be there).
- Scheduled to remove redundant tests from HLS.js to streamline the codebase.
- Preparing to submit pull requests (PRs) to both HLS.js and the Common Media Library repositories to reflect these changes.
- Validate the functionality using id3 streams to make sure everything works

If there are any concerns or questions about this refactor, please feel free to reach out.

**Comment by littlespex** [comment]
I believe this stream has ID3s every 5 seconds: 

https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by littlespex** [comment]
Here are links to the ID3 specs:
- https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-structure.html
- https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html

**Comment by littlespex** [comment]
Here is the corresponding `hls.js` ticket:
- https://github.com/video-dev/hls.js/issues/6168
