### ISSUE TITLE
Integrate CML's ID3 utilities into dash.js

### ISSUE THREAD

**Issue by littlespex** [streaming-video-technology-alliance/common-media-library#60]
**Is your feature request related to a problem? Please describe.**
While `dash.js` does fire emsg events when it encounters ID3 timed metadata, it only passes the raw array buffer in the event payload. Now that CML has a common set of ID3 utilities it is possible to pass out a parsed data payload.

**Describe the solution you'd like**
Integrate CML's ID3 utilities into `dash.js`.

**Comment by dsilhavy** [comment]
Regarding potential DASH testcontent that includes ID3 in EMSG. The AWS streams seem to support this: https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/4577dca5f8a44756875ab5cc913cd1f1/index.mpd

**Comment by littlespex** [comment]
https://github.com/Dash-Industry-Forum/dash.js/pull/4391

**Comment by littlespex** [comment]
This change has been accepted upstream and will be available in `dash.js` versions 5.0.0.
